import json
import time
import uuid
import asyncio
from typing import AsyncGenerator, Dict, Any, Optional

from .state import AgentState
from .graph import evn_graph
from .checkpoints import get_thread_state_snapshot
from .semantic_cache import global_semantic_cache

NODE_DESCRIPTIONS = {
    "classify_intent": "🧠 Đang phân tích ý định người dùng (Pháp lý, Tính cước, Sự cố hay Khiếu nại)...",
    "retrieve_policy_rag": "🔍 Đang truy xuất văn bản quy chuẩn EVN (BM25 + Vector Search)...",
    "calculate_bill": "⚡ Đang tính toán chi tiết hóa đơn theo biểu giá bậc thang 6 mức...",
    "check_outage_compensation": "🔌 Đang tra cứu lịch sử cắt điện & kiểm tra điều kiện bồi thường...",
    "prepare_inspection": "📋 Đang lập phiếu công tác phúc tra & chuẩn bị điểm dừng phê duyệt (HITL)...",
    "rewrite_query": "🔄 Đang viết lại truy vấn để tăng cường độ chính xác trích xuất...",
    "generate_answer": "✨ Đang tổng hợp câu trả lời hoàn chỉnh kèm căn cứ pháp lý EVN..."
}

async def stream_sse_event(event_type: str, data: Dict[str, Any]) -> str:
    """Formats payload according to standard Server-Sent Events specification."""
    json_data = json.dumps(data, ensure_ascii=False)
    return f"event: {event_type}\ndata: {json_data}\n\n"

async def stream_langgraph_execution(
    question: str,
    thread_id: Optional[str] = None,
    customer_id: Optional[str] = None,
    use_semantic_cache: bool = True
) -> AsyncGenerator[str, None]:
    """
    Asynchronous Server-Sent Events generator streaming real-time execution steps,
    tool calls, token-by-token text generation, and state snapshots.
    """
    t_start = time.time()
    active_thread_id = thread_id or f"thread-{uuid.uuid4().hex[:8]}"

    # =========================================================================
    # STEP 1: Semantic Caching Check
    # =========================================================================
    if use_semantic_cache:
        cached_result = global_semantic_cache.get(question)
        if cached_result:
            cached_data, sim_score, matched_q = cached_result
            
            # Emit Cache Hit Event
            yield await stream_sse_event("cache_hit", {
                "matched_question": matched_q,
                "similarity": sim_score,
                "latency_saved_ms": 650.0,
                "message": f"⚡ Semantic Cache Hit ({sim_score * 100:.1f}% tương đồng) - Phản hồi tức thì!"
            })

            # Stream cached answer tokens smoothly
            cached_answer = cached_data.get("answer", "")
            words = cached_answer.split(" ")
            current_text = ""
            for i, word in enumerate(words):
                token = word + (" " if i < len(words) - 1 else "")
                current_text += token
                yield await stream_sse_event("token", {
                    "token": token,
                    "accumulated": current_text,
                    "is_cached": True
                })
                await asyncio.sleep(0.015) # 15ms rapid typewriter effect

            # Emit Done Event
            elapsed_ms = round((time.time() - t_start) * 1000, 2)
            yield await stream_sse_event("done", {
                "thread_id": active_thread_id,
                "status": "COMPLETED",
                "is_paused": False,
                "is_cached": True,
                "state": cached_data.get("state", {}),
                "answer": cached_answer,
                "trace": cached_data.get("trace", []),
                "metrics": {
                    "total_ms": elapsed_ms,
                    "cache_status": "HIT",
                    "similarity": sim_score
                }
            })
            return

    # =========================================================================
    # STEP 2: Live Graph Execution with Streaming Events
    # =========================================================================
    config = {"configurable": {"thread_id": active_thread_id}}
    
    initial_state: AgentState = {
        "question": question,
        "thread_id": active_thread_id,
        "customer_id": customer_id,
        "retry_count": 0,
        "max_retries": 2,
        "retrieved_documents": [],
        "citations": [],
        "trace": [],
        "execution_status": "RUNNING",
        "requires_human": False,
        "needs_compensation_rag": False,
        "needs_retry": False
    }

    # Emit Initialization Event
    yield await stream_sse_event("init", {
        "thread_id": active_thread_id,
        "question": question,
        "customer_id": customer_id,
        "status": "RUNNING",
        "timestamp": time.strftime("%H:%M:%S")
    })

    try:
        # Run graph through real LangGraph runtime
        result_state = evn_graph.invoke(initial_state, config=config)

        # Inspect trace generated by graph execution
        trace_steps = result_state.get("trace", [])
        for step in trace_steps:
            node_name = step.get("node", "unknown")
            description = NODE_DESCRIPTIONS.get(node_name, f"Đang thực thi node {node_name}...")

            # Emit Node Start
            yield await stream_sse_event("node_start", {
                "node": node_name,
                "description": description,
                "timestamp": step.get("timestamp"),
                "duration_ms": step.get("duration_ms", 0)
            })

            # Emit Tool Events if any tools were invoked in this step
            if step.get("tool_called"):
                yield await stream_sse_event("tool_call", {
                    "node": node_name,
                    "tool": step.get("tool_called"),
                    "input": step.get("tool_input"),
                    "observation": step.get("observation")
                })

            # Emit State Update
            if step.get("state_delta"):
                yield await stream_sse_event("state_diff", {
                    "node": node_name,
                    "state_delta": step.get("state_delta"),
                    "decision": step.get("decision")
                })

            await asyncio.sleep(0.05) # Subtle interval for live visual tracking

        # Check if Graph paused at Human-in-the-Loop breakpoint
        snapshot = get_thread_state_snapshot(active_thread_id)
        is_paused = snapshot.get("is_paused", False)

        if is_paused:
            yield await stream_sse_event("interrupt", {
                "thread_id": active_thread_id,
                "status": "PAUSED",
                "next_nodes": snapshot.get("next_nodes", []),
                "reason": "Yêu cầu phê duyệt từ con người (Human-in-the-loop)",
                "state": snapshot.get("state", {}),
                "trace": trace_steps
            })
            return

        # Token-by-token generation streaming for final answer
        final_answer = result_state.get("answer", "")
        if final_answer:
            words = final_answer.split(" ")
            accumulated = ""
            for i, word in enumerate(words):
                token = word + (" " if i < len(words) - 1 else "")
                accumulated += token
                yield await stream_sse_event("token", {
                    "token": token,
                    "accumulated": accumulated,
                    "is_cached": False
                })
                await asyncio.sleep(0.02) # Realistic 20ms token streaming rate

        # Cache the completed execution for future instant retrieval
        if use_semantic_cache and not is_paused:
            global_semantic_cache.set(question, {
                "answer": final_answer,
                "state": result_state,
                "trace": trace_steps
            })

        # Emit Final Done Event
        total_ms = round((time.time() - t_start) * 1000, 2)
        yield await stream_sse_event("done", {
            "thread_id": active_thread_id,
            "status": "COMPLETED",
            "is_paused": False,
            "is_cached": False,
            "state": result_state,
            "answer": final_answer,
            "trace": trace_steps,
            "metrics": {
                "total_ms": total_ms,
                "steps_count": len(trace_steps),
                "cache_status": "MISS (Cached for next run)"
            }
        })

    except Exception as e:
        yield await stream_sse_event("error", {
            "thread_id": active_thread_id,
            "error": str(e),
            "timestamp": time.strftime("%H:%M:%S")
        })
